### ISSUE TITLE
Failure on publishing with masks enabled

### ISSUE THREAD

**Issue by jil24** [labsyspharm/minerva-author#53]
Publishing when I have masks loaded results in this error:
```
2022-10-21 12:06:25,413 - app - ERROR - Exception on /api/render/4dc7c8a388344578a5479ba2660e5a8f [POST]
Traceback (most recent call last):
  File "flask/app.py", line 2525, in wsgi_app
  File "flask/app.py", line 1822, in full_dispatch_request
  File "flask_cors/extension.py", line 165, in wrapped_function
  File "flask/app.py", line 1820, in full_dispatch_request
  File "flask/app.py", line 1796, in dispatch_request
  File "flask_cors/decorator.py", line 128, in wrapped_function
  File "app.py", line 712, in no_cache
  File "app.py", line 1494, in api_render
  File "app.py", line 1236, in make_mask_rows
  File "app.py", line 1239, in <listcomp>
KeyError: 'opacity'
ERROR:app:Exception on /api/render/4dc7c8a388344578a5479ba2660e5a8f [POST]
Traceback (most recent call last):
  File "flask/app.py", line 2525, in wsgi_app
  File "flask/app.py", line 1822, in full_dispatch_request
  File "flask_cors/extension.py", line 165, in wrapped_function
  File "flask/app.py", line 1820, in full_dispatch_request
  File "flask/app.py", line 1796, in dispatch_request
  File "flask_cors/decorator.py", line 128, in wrapped_function
  File "app.py", line 712, in no_cache
  File "app.py", line 1494, in api_render
  File "app.py", line 1236, in make_mask_rows
  File "app.py", line 1239, in <listcomp>
KeyError: 'opacity'
```

Publishing after removing the masks works fine.

**Comment by jil24** [comment]
If I change app.py line 1239 from
`'opacity': c['opacity']` 
to
`'opacity': 1`
Then it publishes correctly, with fully opaque masks. Is this maybe a partly implemented opacity control?

**Comment by adamjtaylor** [comment]
I am also experiencing the same issue and confirm that the fix @jil24 mentions allows publishing (with the set opacity). @jmuhlich is a fix planned for this issue?

**Comment by thejohnhoffer** [comment]
Hi @jil24 @adamjtaylor I have resolved this issue in `v1.11.3`. It turns out `v1.11.2` had the latest version of the python server, incompatible with an outdated version of [the javascript browser](https://github.com/labsyspharm/minerva-author-ui). The `master` branch has the updated solution, with a patched `v1.11.3` executable soon to follow.
